version: '3.1'
services:
  api:
    container_name: next-api
    image: pauloracunha/lamp:2.1.0-php-7.4
    expose:
      - "3000/tcp"
      - "4430/tcp"
    ports:
      - "3000:80"
      - "4430:443"
    networks:
      - ntw
    environment:
      ENVIRONMENT: development
    volumes:
      - ../next-system:/var/www/html/api
      - ./logs/apache2:/var/log/apache2
      - ./apache2/vhosts:/etc/apache2/from-host
      - ./apache2/certs:/etc/apache2/ssl/from-host
    depends_on:
      - db
    links:
      - db
  app:
    container_name: next-app
    build: ../next-app/
    volumes:
        - ../next-app/:/home/node/app/
    ports:
      - "80:4000"
    restart: unless-stopped
    networks:
      - ntw
    depends_on:
      - api
    links:
      - api
  db:
    image: mysql:8
    expose:
      - "3306/tcp"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./datadir:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - ntw

networks:
  ntw:
    name: ntw